"""empty message

Revision ID: 1a91bd0f77ae
Revises: cd71561964f7
Create Date: 2026-02-01 14:54:37.963099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a91bd0f77ae'
down_revision = 'cd71561964f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Post_table',
    sa.Column('User.id', sa.Integer(), nullable=False),
    sa.Column('Post.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Post.id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['User.id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('User.id', 'Post.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_Post_table')
    # ### end Alembic commands ###
